name: Process New Movie Issue

on:
  issues:
    types: [opened]

jobs:
  process:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Process
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
          OMDB_TOKEN: ${{ secrets.OMDB_TOKEN }}
          OPEN_SUBTITLES_TOKEN: ${{ secrets.OPEN_SUBTITLES_TOKEN }}
          SUBDL_TOKEN: ${{ secrets.SUBDL_TOKEN }}
        run: |
          pnpm run load -i ${{ github.event.issue.number }}

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: automated data update
          commit_options: '--no-verify --allow-empty'
