name: Run Script and Update Data Branch

on:
  push:
    branches:
      - main

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
        
      - name: Run script
        run: |
          # Replace this with your script
          echo "Generating output..."
          mkdir output
          echo "Some data output" > output/data.txt

      - name: Checkout data branch
        run: |
          git fetch origin data
          git checkout -b data origin/data || git checkout data

      - name: Copy output to data branch
        run: |
          cp -r output/* .

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update data branch with latest output" || echo "No changes to commit"
          git push origin data
