name: Update

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Download
        run: pnpm run script:download

      - name: Build
        run: pnpm run build

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: automated data update
          commit_options: '--no-verify --allow-empty'        